# Macro file for NeutronSim
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute muonBeamTest.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 0
/run/verbose 1
/event/verbose 0
/tracking/verbose 0 
# 
#
/gun/particle mu-
/gun/energy {KE} GeV
/Output/FileName {KE}GeVMuon{Distance}.root
#
/run/beamOn 1000
