# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0 
# 
# proton 1 GeV to the direction (0.,0.,1.)
#
/gun/particle proton
/gun/energy 1 GeV
#
/run/beamOn 1
